export const ORDER_CONNECTION_INIT: 'ORDER_CONNECTION_INIT' =
  'ORDER_CONNECTION_INIT';
export const ORDER_CONNECTION_SUCCESS: 'ORDER_CONNECTION_SUCCESS' =
  'ORDER_CONNECTION_SUCCESS';
export const ORDER_CONNECTION_CLOSE: 'ORDER_CONNECTION_CLOSE' =
  'ORDER_CONNECTION_CLOSE';
export const ORDER_CONNECTION_CLOSED: 'ORDER_CONNECTION_CLOSED' =
  'ORDER_CONNECTION_CLOSED';
export const ORDER_CONNECTION_ERROR: 'ORDER_CONNECTION_ERROR' =
  'ORDER_CONNECTION_ERROR';
export const ORDER_GET_MESSAGE: 'ORDER_GET_MESSAGE' = 'ORDER_GET_MESSAGE';

export const orderWsActions = {
  wsInit: ORDER_CONNECTION_INIT,
  wsClose: ORDER_CONNECTION_CLOSE,
  onOpen: ORDER_CONNECTION_SUCCESS,
  onClose: ORDER_CONNECTION_CLOSED,
  onMessage: ORDER_GET_MESSAGE,
  onError: ORDER_CONNECTION_ERROR,
};
